/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.made_lavant.view;

import com.made_lavant.base.Cliente;
import com.made_lavant.base.Endereco;
import com.made_lavant.dados.ClienteDados;

/**
 *
 * @author ewe88
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public CadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nome_cadastroCliente = new javax.swing.JTextField();
        cidade_cadastroCliente = new javax.swing.JTextField();
        rua_cadastroCliente = new javax.swing.JTextField();
        confirmarBTN_cadastroCliente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bairro_cadastroCliente = new javax.swing.JTextField();
        numero_cadastroCliente = new javax.swing.JTextField();
        uf_cadastroCliente = new javax.swing.JTextField();
        cpf_cadastroCliente = new javax.swing.JTextField();
        cep_cadastroCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_sairCadastroCliente = new javax.swing.JButton();
        clienteCadastrado = new javax.swing.JLabel();
        clienteCadastrado.setVisible(false);
        jLabel12 = new javax.swing.JLabel();
        senha_cadastroCliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");

        jPanel1.setBackground(new java.awt.Color(45, 48, 71));

        jLabel1.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(232, 72, 85));
        jLabel1.setText("Cadastro do Cliente");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(232, 72, 85));
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(232, 72, 85));
        jLabel3.setText("Cidade");

        jLabel4.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(232, 72, 85));
        jLabel4.setText("Rua");

        nome_cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_cadastroClienteActionPerformed(evt);
            }
        });

        cidade_cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidade_cadastroClienteActionPerformed(evt);
            }
        });

        rua_cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rua_cadastroClienteActionPerformed(evt);
            }
        });

        confirmarBTN_cadastroCliente.setBackground(new java.awt.Color(255, 253, 130));
        confirmarBTN_cadastroCliente.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        confirmarBTN_cadastroCliente.setForeground(new java.awt.Color(232, 72, 85));
        confirmarBTN_cadastroCliente.setText("Confirmar");
        confirmarBTN_cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarBTN_cadastroClienteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(232, 72, 85));
        jLabel5.setText("Bairro");

        jLabel6.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(232, 72, 85));
        jLabel6.setText("Número");

        jLabel7.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(232, 72, 85));
        jLabel7.setText("UF");

        jLabel8.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(232, 72, 85));
        jLabel8.setText("CEP");

        jLabel9.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(232, 72, 85));
        jLabel9.setText("CPF");

        numero_cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_cadastroClienteActionPerformed(evt);
            }
        });

        cpf_cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpf_cadastroClienteActionPerformed(evt);
            }
        });

        cep_cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cep_cadastroClienteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Colonna MT", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 253, 130));
        jLabel10.setText("MADE");

        jLabel11.setFont(new java.awt.Font("Colonna MT", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(232, 72, 85));
        jLabel11.setText("Lavant");

        btn_sairCadastroCliente.setBackground(new java.awt.Color(255, 253, 130));
        btn_sairCadastroCliente.setFont(new java.awt.Font("Colonna MT", 1, 14)); // NOI18N
        btn_sairCadastroCliente.setForeground(new java.awt.Color(232, 72, 85));
        btn_sairCadastroCliente.setText("Sair");
        btn_sairCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairCadastroClienteActionPerformed(evt);
            }
        });

        clienteCadastrado.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        clienteCadastrado.setForeground(new java.awt.Color(232, 72, 85));
        clienteCadastrado.setText("Cliente já cadastrado");

        jLabel12.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(232, 72, 85));
        jLabel12.setText("Senha");

        senha_cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senha_cadastroClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(uf_cadastroCliente)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)
                                        .addGap(12, 12, 12)
                                        .addComponent(cpf_cadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bairro_cadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cep_cadastroCliente)
                                    .addComponent(numero_cadastroCliente)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_sairCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rua_cadastroCliente)
                                    .addComponent(nome_cadastroCliente)
                                    .addComponent(cidade_cadastroCliente)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(258, 258, 258)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(clienteCadastrado)
                .addGap(110, 110, 110)
                .addComponent(confirmarBTN_cadastroCliente)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(senha_cadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_sairCadastroCliente)
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nome_cadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cidade_cadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rua_cadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bairro_cadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(numero_cadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cep_cadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cpf_cadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(uf_cadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(senha_cadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteCadastrado)
                    .addComponent(confirmarBTN_cadastroCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nome_cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_cadastroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_cadastroClienteActionPerformed

    private void cidade_cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidade_cadastroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidade_cadastroClienteActionPerformed

    private void rua_cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rua_cadastroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rua_cadastroClienteActionPerformed

    private void cep_cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cep_cadastroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cep_cadastroClienteActionPerformed

    private void cpf_cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf_cadastroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpf_cadastroClienteActionPerformed

    private void btn_sairCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairCadastroClienteActionPerformed
        //deixa de mostrar a tela atual e mostra a tela de login
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btn_sairCadastroClienteActionPerformed

    private void confirmarBTN_cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarBTN_cadastroClienteActionPerformed
        //diz se o cadastro pode ou não ser realizado
        boolean cadastro = true;
        //verifica se o campo de CPF está preenchido
        if (cpf_cadastroCliente.getText().equals("")) {
            //se não estiver o cadastro não pode ser realizado
            cpf_cadastroCliente.setText("Campo obrigatório");
            cadastro = false;
        } else {
            //verfica se o cpf é válido, se não for ele não pode ser cadastrado
            cadastro = Cliente.verificaCPF(cpf_cadastroCliente.getText());
            if (!cadastro) {
                cpf_cadastroCliente.setText("CPF inválido");
            } else {
                //verifica se o cliente já está cadastrado, se ele já estiver, não pode ser cadastrado novamente
                ClienteDados cliendeDados = new ClienteDados();
                if (cliendeDados.buscarCPF(cpf_cadastroCliente.getText()) != null) {
                    cadastro = false;
                    clienteCadastrado.setVisible(true);
                } else {
                    clienteCadastrado.setVisible(false);
                }
            }
        }
        //verifica se o campo de nome está preenchido
        if (nome_cadastroCliente.getText().equals("") || nome_cadastroCliente.getText().equals("Campo obrigatório")) {
            //se não estiver o cadastro não pode ser realizado
            nome_cadastroCliente.setText("Campo obrigatório");
            cadastro = false;
        }
        //verifica se o campo senha foi preenchido
        if (senha_cadastroCliente.getText().equals("") || senha_cadastroCliente.getText().equals("Campo obrigatório")) {
            //se não estiver o cadastro não pode ser realizado
            senha_cadastroCliente.setText("Campo obrigatório");
            cadastro = false;
        }

        //verifica se algum campo referente ao endereço foi cadastrado, se um deles for cadastrado, todos devem ser cadastrados
        if (!(cidade_cadastroCliente.getText().equals("") && rua_cadastroCliente.getText().equals("") && bairro_cadastroCliente.getText().equals("") && numero_cadastroCliente.getText().equals("") && uf_cadastroCliente.getText().equals("") && cep_cadastroCliente.getText().equals(""))) {
            if (cidade_cadastroCliente.getText().equals("") || cidade_cadastroCliente.getText().equals("Campo obrigatório se for cadastrar o endereço")) {
                cidade_cadastroCliente.setText("Campo obrigatório se for cadastrar o endereço");
                cadastro = false;
            }
            if (bairro_cadastroCliente.getText().equals("") || bairro_cadastroCliente.getText().equals("Campo obrigatório se for cadastrar o endereço")) {
                bairro_cadastroCliente.setText("Campo obrigatório se for cadastrar o endereço");
                cadastro = false;
            }
            if (rua_cadastroCliente.getText().equals("") || rua_cadastroCliente.getText().equals("Campo obrigatório se for cadastrar o endereço")) {
                rua_cadastroCliente.setText("Campo obrigatório se for cadastrar o endereço");
                cadastro = false;
            }
            if (uf_cadastroCliente.getText().equals("") || uf_cadastroCliente.getText().equals("Campo obrigatório se for cadastrar o endereço")) {
                uf_cadastroCliente.setText("Campo obrigatório se for cadastrar o endereço");
                cadastro = false;
            }
            if (numero_cadastroCliente.getText().equals("") || numero_cadastroCliente.getText().equals("Campo obrigatório se for cadastrar o endereço")) {
                numero_cadastroCliente.setText("Campo obrigatório se for cadastrar o endereço");
                cadastro = false;
            }
            if (cep_cadastroCliente.getText().equals("") || cep_cadastroCliente.getText().equals("Campo obrigatório se for cadastrar o endereço")) {
                cep_cadastroCliente.setText("Campo obrigatório se for cadastrar o endereço");
                cadastro = false;
            }
            if (cadastro) {
                //com todos os campos de endereço preenchidos, o cadastro será feito com o endereço
                Endereco endereco = new Endereco(cidade_cadastroCliente.getText(), cep_cadastroCliente.getText(), uf_cadastroCliente.getText(), bairro_cadastroCliente.getText(), rua_cadastroCliente.getText(), numero_cadastroCliente.getText());
                new Cliente(nome_cadastroCliente.getText(), endereco, cpf_cadastroCliente.getText(), senha_cadastroCliente.getText());
            }
            //se nenhum campo de endereço estiver cadastrado, o cadastro será feito sem o endereço
        } else {
            if (cadastro) {
                new Cliente(nome_cadastroCliente.getText(), cpf_cadastroCliente.getText(), senha_cadastroCliente.getText());
            }
        }
        //retorna para a tela de login se o cadastro foi realizado
        if (cadastro) {
            this.setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_confirmarBTN_cadastroClienteActionPerformed

    private void numero_cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_cadastroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_cadastroClienteActionPerformed

    private void senha_cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senha_cadastroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senha_cadastroClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairro_cadastroCliente;
    private javax.swing.JButton btn_sairCadastroCliente;
    private javax.swing.JTextField cep_cadastroCliente;
    private javax.swing.JTextField cidade_cadastroCliente;
    private javax.swing.JLabel clienteCadastrado;
    private javax.swing.JButton confirmarBTN_cadastroCliente;
    private javax.swing.JTextField cpf_cadastroCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nome_cadastroCliente;
    private javax.swing.JTextField numero_cadastroCliente;
    private javax.swing.JTextField rua_cadastroCliente;
    private javax.swing.JTextField senha_cadastroCliente;
    private javax.swing.JTextField uf_cadastroCliente;
    // End of variables declaration//GEN-END:variables
}
