/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.made_lavant.view;

/**
 *
 * @author Daniel
 */
public class CrudFuncionarios extends javax.swing.JFrame {

    /**
     * Creates new form CRUDFUNCIONARIOS
     */
    public CrudFuncionarios() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topicoIdLB_CRF = new javax.swing.JLabel();
        nomeLB_CRF = new javax.swing.JLabel();
        idLB_CRF = new javax.swing.JLabel();
        madeLB_CRF = new javax.swing.JLabel();
        addFuncBTN_CRF = new javax.swing.JButton();
        lavantLB_CRF = new javax.swing.JLabel();
        removerBTN_CRF = new javax.swing.JButton();
        sairBTN_CRF = new javax.swing.JButton();
        editarBTN_CRF = new javax.swing.JButton();
        descricaoBTN_CRF = new javax.swing.JButton();
        voltarBTN_CRF = new javax.swing.JButton();
        topicoNomeLB_CRF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de Funcionários");
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(45, 48, 71));

        topicoIdLB_CRF.setFont(new java.awt.Font("Colonna MT", 1, 16)); // NOI18N
        topicoIdLB_CRF.setForeground(new java.awt.Color(232, 72, 85));
        topicoIdLB_CRF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topicoIdLB_CRF.setText("Identificação");

        nomeLB_CRF.setBackground(new java.awt.Color(255, 255, 255));
        nomeLB_CRF.setFont(new java.awt.Font("Colonna MT", 1, 13)); // NOI18N
        nomeLB_CRF.setForeground(new java.awt.Color(255, 253, 130));
        nomeLB_CRF.setText("Nome");

        idLB_CRF.setBackground(new java.awt.Color(255, 255, 255));
        idLB_CRF.setFont(new java.awt.Font("Colonna MT", 1, 13)); // NOI18N
        idLB_CRF.setForeground(new java.awt.Color(255, 253, 130));
        idLB_CRF.setText("000");

        madeLB_CRF.setBackground(new java.awt.Color(255, 253, 130));
        madeLB_CRF.setFont(new java.awt.Font("Colonna MT", 0, 20)); // NOI18N
        madeLB_CRF.setForeground(new java.awt.Color(255, 253, 130));
        madeLB_CRF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        madeLB_CRF.setText("MADE");
        madeLB_CRF.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        addFuncBTN_CRF.setBackground(new java.awt.Color(255, 253, 130));
        addFuncBTN_CRF.setFont(new java.awt.Font("Colonna MT", 1, 14)); // NOI18N
        addFuncBTN_CRF.setForeground(new java.awt.Color(232, 72, 85));
        addFuncBTN_CRF.setText("Adicionar Funcionário");
        addFuncBTN_CRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFuncBTN_CRFActionPerformed(evt);
            }
        });

        lavantLB_CRF.setFont(new java.awt.Font("Colonna MT", 1, 20)); // NOI18N
        lavantLB_CRF.setForeground(new java.awt.Color(232, 72, 85));
        lavantLB_CRF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lavantLB_CRF.setText("Lavant");

        removerBTN_CRF.setBackground(new java.awt.Color(255, 253, 130));
        removerBTN_CRF.setFont(new java.awt.Font("Colonna MT", 1, 13)); // NOI18N
        removerBTN_CRF.setForeground(new java.awt.Color(232, 72, 85));
        removerBTN_CRF.setText("Remover");
        removerBTN_CRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerBTN_CRFActionPerformed(evt);
            }
        });

        sairBTN_CRF.setBackground(new java.awt.Color(255, 253, 130));
        sairBTN_CRF.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        sairBTN_CRF.setForeground(new java.awt.Color(232, 72, 85));
        sairBTN_CRF.setText("Sair");
        sairBTN_CRF.setToolTipText("");
        sairBTN_CRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBTN_CRFActionPerformed(evt);
            }
        });

        editarBTN_CRF.setBackground(new java.awt.Color(255, 253, 130));
        editarBTN_CRF.setFont(new java.awt.Font("Colonna MT", 1, 13)); // NOI18N
        editarBTN_CRF.setForeground(new java.awt.Color(232, 72, 85));
        editarBTN_CRF.setText("Editar");
        editarBTN_CRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBTN_CRFActionPerformed(evt);
            }
        });

        descricaoBTN_CRF.setBackground(new java.awt.Color(255, 253, 130));
        descricaoBTN_CRF.setFont(new java.awt.Font("Colonna MT", 1, 13)); // NOI18N
        descricaoBTN_CRF.setForeground(new java.awt.Color(232, 72, 85));
        descricaoBTN_CRF.setText("Descrição");
        descricaoBTN_CRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoBTN_CRFActionPerformed(evt);
            }
        });

        voltarBTN_CRF.setBackground(new java.awt.Color(255, 253, 130));
        voltarBTN_CRF.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        voltarBTN_CRF.setForeground(new java.awt.Color(232, 72, 85));
        voltarBTN_CRF.setText("Voltar");
        voltarBTN_CRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBTN_CRFActionPerformed(evt);
            }
        });

        topicoNomeLB_CRF.setBackground(new java.awt.Color(255, 253, 130));
        topicoNomeLB_CRF.setFont(new java.awt.Font("Colonna MT", 1, 16)); // NOI18N
        topicoNomeLB_CRF.setForeground(new java.awt.Color(232, 72, 85));
        topicoNomeLB_CRF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topicoNomeLB_CRF.setText("Nome");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sairBTN_CRF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(voltarBTN_CRF)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(topicoNomeLB_CRF)
                        .addGap(149, 149, 149)
                        .addComponent(topicoIdLB_CRF))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nomeLB_CRF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(idLB_CRF, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(151, 151, 151)
                .addComponent(removerBTN_CRF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editarBTN_CRF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descricaoBTN_CRF)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addFuncBTN_CRF)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lavantLB_CRF, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(madeLB_CRF))))
                .addGap(300, 300, 300))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sairBTN_CRF)
                    .addComponent(voltarBTN_CRF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(madeLB_CRF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lavantLB_CRF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addFuncBTN_CRF)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topicoNomeLB_CRF)
                    .addComponent(topicoIdLB_CRF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLB_CRF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLB_CRF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removerBTN_CRF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarBTN_CRF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descricaoBTN_CRF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFuncBTN_CRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFuncBTN_CRFActionPerformed
        this.setVisible(false);
        new CadastroFuncionario().setVisible(true);    
    }//GEN-LAST:event_addFuncBTN_CRFActionPerformed

    private void sairBTN_CRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBTN_CRFActionPerformed
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_sairBTN_CRFActionPerformed

    private void descricaoBTN_CRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoBTN_CRFActionPerformed
        this.setVisible(false);
        new PerfilFuncionario().setVisible(true);
    }//GEN-LAST:event_descricaoBTN_CRFActionPerformed

    private void editarBTN_CRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBTN_CRFActionPerformed
        this.setVisible(false);
        new EditarDadosFuncionario().setVisible(true);
    }//GEN-LAST:event_editarBTN_CRFActionPerformed

    private void voltarBTN_CRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBTN_CRFActionPerformed
        this.setVisible(false);
        new InicioGerente().setVisible(true);
    }//GEN-LAST:event_voltarBTN_CRFActionPerformed

    private void removerBTN_CRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerBTN_CRFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removerBTN_CRFActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFuncBTN_CRF;
    private javax.swing.JButton descricaoBTN_CRF;
    private javax.swing.JButton editarBTN_CRF;
    private javax.swing.JLabel idLB_CRF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lavantLB_CRF;
    private javax.swing.JLabel madeLB_CRF;
    private javax.swing.JLabel nomeLB_CRF;
    private javax.swing.JButton removerBTN_CRF;
    private javax.swing.JButton sairBTN_CRF;
    private javax.swing.JLabel topicoIdLB_CRF;
    private javax.swing.JLabel topicoNomeLB_CRF;
    private javax.swing.JButton voltarBTN_CRF;
    // End of variables declaration//GEN-END:variables
}
