/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.made_lavant.view;

/**
 *
 * @author Marcio
 */
public class DetalheCarrinho extends javax.swing.JFrame {

    /**
     * Creates new form DetalheCarrinho
     */
    public DetalheCarrinho() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        topicoTotalLB_DC = new javax.swing.JLabel();
        madeLB_DC = new javax.swing.JLabel();
        lavantLB_DC = new javax.swing.JLabel();
        voltarBTN_DC = new javax.swing.JButton();
        topicoNomeLB_DC = new javax.swing.JLabel();
        topicoCodLB_DC = new javax.swing.JLabel();
        topicoQuantiLB_DC = new javax.swing.JLabel();
        topicoValiLB_DC = new javax.swing.JLabel();
        topicoPrecoLB_DC = new javax.swing.JLabel();
        nomeLB_DC = new javax.swing.JLabel();
        codLB_DC = new javax.swing.JLabel();
        precoLB_DC = new javax.swing.JLabel();
        quantiLB_DC = new javax.swing.JLabel();
        valiLB_DC = new javax.swing.JLabel();
        totalLB_DC = new javax.swing.JLabel();
        sairBTN_DC = new javax.swing.JButton();

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Colonna MT", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 253, 130));
        jLabel18.setText("000");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Colonna MT", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 253, 130));
        jLabel20.setText("dd/mm/aaaa");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 48, 71));

        topicoTotalLB_DC.setBackground(new java.awt.Color(255, 253, 130));
        topicoTotalLB_DC.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        topicoTotalLB_DC.setForeground(new java.awt.Color(232, 72, 85));
        topicoTotalLB_DC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topicoTotalLB_DC.setText("Total");

        madeLB_DC.setBackground(new java.awt.Color(255, 253, 130));
        madeLB_DC.setFont(new java.awt.Font("Colonna MT", 0, 20)); // NOI18N
        madeLB_DC.setForeground(new java.awt.Color(255, 253, 130));
        madeLB_DC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        madeLB_DC.setText("MADE");
        madeLB_DC.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lavantLB_DC.setFont(new java.awt.Font("Colonna MT", 1, 20)); // NOI18N
        lavantLB_DC.setForeground(new java.awt.Color(232, 72, 85));
        lavantLB_DC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lavantLB_DC.setText("Lavant");

        voltarBTN_DC.setBackground(new java.awt.Color(255, 253, 130));
        voltarBTN_DC.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        voltarBTN_DC.setForeground(new java.awt.Color(232, 72, 85));
        voltarBTN_DC.setText("Voltar");
        voltarBTN_DC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBTN_DCActionPerformed(evt);
            }
        });

        topicoNomeLB_DC.setBackground(new java.awt.Color(255, 253, 130));
        topicoNomeLB_DC.setFont(new java.awt.Font("Colonna MT", 1, 16)); // NOI18N
        topicoNomeLB_DC.setForeground(new java.awt.Color(232, 72, 85));
        topicoNomeLB_DC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        topicoNomeLB_DC.setText("Nome");

        topicoCodLB_DC.setFont(new java.awt.Font("Colonna MT", 1, 16)); // NOI18N
        topicoCodLB_DC.setForeground(new java.awt.Color(232, 72, 85));
        topicoCodLB_DC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        topicoCodLB_DC.setText("Código");

        topicoQuantiLB_DC.setFont(new java.awt.Font("Colonna MT", 1, 16)); // NOI18N
        topicoQuantiLB_DC.setForeground(new java.awt.Color(232, 72, 85));
        topicoQuantiLB_DC.setText("Quantidade");

        topicoValiLB_DC.setFont(new java.awt.Font("Colonna MT", 1, 16)); // NOI18N
        topicoValiLB_DC.setForeground(new java.awt.Color(232, 72, 85));
        topicoValiLB_DC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        topicoValiLB_DC.setText("Validade");

        topicoPrecoLB_DC.setFont(new java.awt.Font("Colonna MT", 1, 16)); // NOI18N
        topicoPrecoLB_DC.setForeground(new java.awt.Color(232, 72, 85));
        topicoPrecoLB_DC.setText("Preço");

        nomeLB_DC.setBackground(new java.awt.Color(255, 255, 255));
        nomeLB_DC.setFont(new java.awt.Font("Colonna MT", 1, 13)); // NOI18N
        nomeLB_DC.setForeground(new java.awt.Color(255, 253, 130));
        nomeLB_DC.setText("Nome");

        codLB_DC.setBackground(new java.awt.Color(255, 255, 255));
        codLB_DC.setFont(new java.awt.Font("Colonna MT", 1, 13)); // NOI18N
        codLB_DC.setForeground(new java.awt.Color(255, 253, 130));
        codLB_DC.setText("000");

        precoLB_DC.setBackground(new java.awt.Color(255, 255, 255));
        precoLB_DC.setFont(new java.awt.Font("Colonna MT", 1, 13)); // NOI18N
        precoLB_DC.setForeground(new java.awt.Color(255, 253, 130));
        precoLB_DC.setText("00,00");

        quantiLB_DC.setBackground(new java.awt.Color(255, 255, 255));
        quantiLB_DC.setFont(new java.awt.Font("Colonna MT", 1, 13)); // NOI18N
        quantiLB_DC.setForeground(new java.awt.Color(255, 253, 130));
        quantiLB_DC.setText("000");

        valiLB_DC.setBackground(new java.awt.Color(255, 255, 255));
        valiLB_DC.setFont(new java.awt.Font("Colonna MT", 1, 13)); // NOI18N
        valiLB_DC.setForeground(new java.awt.Color(255, 253, 130));
        valiLB_DC.setText("dd/mm/aaaa");

        totalLB_DC.setBackground(new java.awt.Color(255, 255, 255));
        totalLB_DC.setFont(new java.awt.Font("Colonna MT", 1, 13)); // NOI18N
        totalLB_DC.setForeground(new java.awt.Color(255, 253, 130));
        totalLB_DC.setText("000");

        sairBTN_DC.setBackground(new java.awt.Color(255, 253, 130));
        sairBTN_DC.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        sairBTN_DC.setForeground(new java.awt.Color(232, 72, 85));
        sairBTN_DC.setText("Sair");
        sairBTN_DC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBTN_DCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 27, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lavantLB_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(madeLB_DC)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nomeLB_DC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(topicoNomeLB_DC, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(topicoCodLB_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codLB_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(topicoQuantiLB_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)
                                        .addComponent(topicoValiLB_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(quantiLB_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(valiLB_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(precoLB_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(topicoPrecoLB_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 80, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sairBTN_DC)
                        .addGap(18, 18, 18)
                        .addComponent(voltarBTN_DC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(topicoTotalLB_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalLB_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topicoTotalLB_DC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(voltarBTN_DC)
                    .addComponent(totalLB_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sairBTN_DC))
                .addGap(43, 43, 43)
                .addComponent(madeLB_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lavantLB_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topicoValiLB_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topicoCodLB_DC)
                    .addComponent(topicoQuantiLB_DC)
                    .addComponent(topicoPrecoLB_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topicoNomeLB_DC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLB_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precoLB_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codLB_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valiLB_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantiLB_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(301, 301, 301))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarBTN_DCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBTN_DCActionPerformed
        this.setVisible(false);
        new CrudCarrinho().setVisible(true);
    }//GEN-LAST:event_voltarBTN_DCActionPerformed

    private void sairBTN_DCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBTN_DCActionPerformed
       this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_sairBTN_DCActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codLB_DC;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lavantLB_DC;
    private javax.swing.JLabel madeLB_DC;
    private javax.swing.JLabel nomeLB_DC;
    private javax.swing.JLabel precoLB_DC;
    private javax.swing.JLabel quantiLB_DC;
    private javax.swing.JButton sairBTN_DC;
    private javax.swing.JLabel topicoCodLB_DC;
    private javax.swing.JLabel topicoNomeLB_DC;
    private javax.swing.JLabel topicoPrecoLB_DC;
    private javax.swing.JLabel topicoQuantiLB_DC;
    private javax.swing.JLabel topicoTotalLB_DC;
    private javax.swing.JLabel topicoValiLB_DC;
    private javax.swing.JLabel totalLB_DC;
    private javax.swing.JLabel valiLB_DC;
    private javax.swing.JButton voltarBTN_DC;
    // End of variables declaration//GEN-END:variables
}
