/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.made_lavant.view;

/**
 *
 * @author matheusreis
 */
public class TelaCarrinho extends javax.swing.JFrame {

    /**
     * Creates new form TelaCarrinho
     */
    public TelaCarrinho() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        valLB_TC = new javax.swing.JLabel();
        topicoTotalLB_TC = new javax.swing.JLabel();
        totalLB_TC = new javax.swing.JLabel();
        madeLB_TC = new javax.swing.JLabel();
        lavantLB_TC = new javax.swing.JLabel();
        sairBTN_TC = new javax.swing.JButton();
        topicoNomeLB_TC = new javax.swing.JLabel();
        topicoCodLB_TC = new javax.swing.JLabel();
        TopicoQuantiLB_TC = new javax.swing.JLabel();
        topicoValLB_TC = new javax.swing.JLabel();
        quantiLB_TC = new javax.swing.JLabel();
        nomeLB_TC = new javax.swing.JLabel();
        addProdBTN_TC = new javax.swing.JButton();
        codLB_TC = new javax.swing.JLabel();
        topicoPrecoLB_TC = new javax.swing.JLabel();
        precoLB_TC = new javax.swing.JLabel();
        removerBTN_TC = new javax.swing.JButton();
        voltarBTN_TC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Carrinho");

        jPanel1.setBackground(new java.awt.Color(45, 48, 71));

        valLB_TC.setBackground(new java.awt.Color(255, 255, 255));
        valLB_TC.setFont(new java.awt.Font("Colonna MT", 1, 13)); // NOI18N
        valLB_TC.setForeground(new java.awt.Color(255, 253, 130));
        valLB_TC.setText("dd/mm/aaaa");

        topicoTotalLB_TC.setBackground(new java.awt.Color(255, 253, 130));
        topicoTotalLB_TC.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        topicoTotalLB_TC.setForeground(new java.awt.Color(232, 72, 85));
        topicoTotalLB_TC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topicoTotalLB_TC.setText("Total");

        totalLB_TC.setFont(new java.awt.Font("Colonna MT", 1, 11)); // NOI18N
        totalLB_TC.setForeground(new java.awt.Color(255, 255, 255));
        totalLB_TC.setText("jLabel11");

        madeLB_TC.setBackground(new java.awt.Color(255, 253, 130));
        madeLB_TC.setFont(new java.awt.Font("Colonna MT", 0, 20)); // NOI18N
        madeLB_TC.setForeground(new java.awt.Color(255, 253, 130));
        madeLB_TC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        madeLB_TC.setText("MADE");
        madeLB_TC.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lavantLB_TC.setFont(new java.awt.Font("Colonna MT", 1, 20)); // NOI18N
        lavantLB_TC.setForeground(new java.awt.Color(232, 72, 85));
        lavantLB_TC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lavantLB_TC.setText("Lavant");

        sairBTN_TC.setBackground(new java.awt.Color(255, 253, 130));
        sairBTN_TC.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        sairBTN_TC.setForeground(new java.awt.Color(232, 72, 85));
        sairBTN_TC.setText("Sair");
        sairBTN_TC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBTN_TCActionPerformed(evt);
            }
        });

        topicoNomeLB_TC.setBackground(new java.awt.Color(255, 253, 130));
        topicoNomeLB_TC.setFont(new java.awt.Font("Colonna MT", 1, 16)); // NOI18N
        topicoNomeLB_TC.setForeground(new java.awt.Color(232, 72, 85));
        topicoNomeLB_TC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        topicoNomeLB_TC.setText("Nome");

        topicoCodLB_TC.setFont(new java.awt.Font("Colonna MT", 1, 16)); // NOI18N
        topicoCodLB_TC.setForeground(new java.awt.Color(232, 72, 85));
        topicoCodLB_TC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        topicoCodLB_TC.setText("Código");

        TopicoQuantiLB_TC.setFont(new java.awt.Font("Colonna MT", 1, 16)); // NOI18N
        TopicoQuantiLB_TC.setForeground(new java.awt.Color(232, 72, 85));
        TopicoQuantiLB_TC.setText("Quantidade");

        topicoValLB_TC.setFont(new java.awt.Font("Colonna MT", 1, 16)); // NOI18N
        topicoValLB_TC.setForeground(new java.awt.Color(232, 72, 85));
        topicoValLB_TC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        topicoValLB_TC.setText("Validade");

        quantiLB_TC.setFont(new java.awt.Font("Colonna MT", 1, 13)); // NOI18N
        quantiLB_TC.setForeground(new java.awt.Color(255, 253, 130));
        quantiLB_TC.setText("000");

        nomeLB_TC.setBackground(new java.awt.Color(255, 255, 255));
        nomeLB_TC.setFont(new java.awt.Font("Colonna MT", 1, 13)); // NOI18N
        nomeLB_TC.setForeground(new java.awt.Color(255, 253, 130));
        nomeLB_TC.setText("Nome");

        addProdBTN_TC.setBackground(new java.awt.Color(255, 253, 130));
        addProdBTN_TC.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        addProdBTN_TC.setForeground(new java.awt.Color(232, 72, 85));
        addProdBTN_TC.setText("Adicionar Produto");
        addProdBTN_TC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProdBTN_TCActionPerformed(evt);
            }
        });

        codLB_TC.setBackground(new java.awt.Color(255, 255, 255));
        codLB_TC.setFont(new java.awt.Font("Colonna MT", 1, 13)); // NOI18N
        codLB_TC.setForeground(new java.awt.Color(255, 253, 130));
        codLB_TC.setText("000");

        topicoPrecoLB_TC.setFont(new java.awt.Font("Colonna MT", 1, 16)); // NOI18N
        topicoPrecoLB_TC.setForeground(new java.awt.Color(232, 72, 85));
        topicoPrecoLB_TC.setText("Preço");

        precoLB_TC.setFont(new java.awt.Font("Colonna MT", 1, 13)); // NOI18N
        precoLB_TC.setForeground(new java.awt.Color(255, 253, 130));
        precoLB_TC.setText("00.00");

        removerBTN_TC.setBackground(new java.awt.Color(255, 253, 130));
        removerBTN_TC.setForeground(new java.awt.Color(232, 72, 85));
        removerBTN_TC.setText("Remover");

        voltarBTN_TC.setBackground(new java.awt.Color(255, 253, 130));
        voltarBTN_TC.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        voltarBTN_TC.setForeground(new java.awt.Color(232, 72, 85));
        voltarBTN_TC.setText("Voltar");
        voltarBTN_TC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBTN_TCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(sairBTN_TC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(voltarBTN_TC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(topicoTotalLB_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalLB_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nomeLB_TC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(topicoNomeLB_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(topicoCodLB_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codLB_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TopicoQuantiLB_TC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quantiLB_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(topicoValLB_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valLB_TC, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(precoLB_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removerBTN_TC))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(topicoPrecoLB_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 68, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addProdBTN_TC)
                            .addComponent(lavantLB_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(madeLB_TC))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topicoTotalLB_TC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sairBTN_TC)
                    .addComponent(totalLB_TC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(voltarBTN_TC))
                .addGap(30, 30, 30)
                .addComponent(madeLB_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lavantLB_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addProdBTN_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topicoValLB_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topicoCodLB_TC)
                    .addComponent(TopicoQuantiLB_TC)
                    .addComponent(topicoPrecoLB_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topicoNomeLB_TC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeLB_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(codLB_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(valLB_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(quantiLB_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(precoLB_TC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removerBTN_TC)))
                .addGap(316, 316, 316))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairBTN_TCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBTN_TCActionPerformed
         this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_sairBTN_TCActionPerformed

    private void addProdBTN_TCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProdBTN_TCActionPerformed
        this.setVisible(false);
        new CrudProdutos_Cliente().setVisible(true);
    }//GEN-LAST:event_addProdBTN_TCActionPerformed

    private void voltarBTN_TCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBTN_TCActionPerformed
        this.setVisible(false);
        new InicioCliente().setVisible(true);
    }//GEN-LAST:event_voltarBTN_TCActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TopicoQuantiLB_TC;
    private javax.swing.JButton addProdBTN_TC;
    private javax.swing.JLabel codLB_TC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lavantLB_TC;
    private javax.swing.JLabel madeLB_TC;
    private javax.swing.JLabel nomeLB_TC;
    private javax.swing.JLabel precoLB_TC;
    private javax.swing.JLabel quantiLB_TC;
    private javax.swing.JButton removerBTN_TC;
    private javax.swing.JButton sairBTN_TC;
    private javax.swing.JLabel topicoCodLB_TC;
    private javax.swing.JLabel topicoNomeLB_TC;
    private javax.swing.JLabel topicoPrecoLB_TC;
    private javax.swing.JLabel topicoTotalLB_TC;
    private javax.swing.JLabel topicoValLB_TC;
    private javax.swing.JLabel totalLB_TC;
    private javax.swing.JLabel valLB_TC;
    private javax.swing.JButton voltarBTN_TC;
    // End of variables declaration//GEN-END:variables
}
